---
- name: Add rules for firewalld
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
    - 8300/tcp
    - 8301/tcp
    - 8302/tcp
    - 8400/tcp
    - 8500/tcp
    - 8600/tcp
    - 8301/udp
    - 8302/udp
    - 8600/udp
