- hosts: "{{ target }}"
  become: yes
  gather_facts: yes
  roles:
    - { role: elastic_prepare, tags: ['eprepare','full'] }
    - { role: elastic_install, tags: ['einstall','full'] }
    - { role: elastic_tunning, tags: ['etunning','full'] }
    - { role: elastic_check, tags: ['echeck','full'] }
