- hosts: prometheus
  become: yes
  gather_facts: yes
  roles:
    - { role: prometheus_upload, tags: ['prometheusupload','full'] }
    - { role: prometheus_addpath, tags: ['prometheusaddpath','full'] }
    - { role: prometheus_run, tags: ['prometheusrun','full'] }
    - { role: prometheus_start, tags: ['prometheusstart','full'] }
    - { role: prometheus_firewalld, tags: ['prometheusfirewalld','full'] }
