---
- name: Check elastic run
  uri:
    url: http://{{ hostvars[inventory_hostname].ansible_host }}:{{ elasticport | default('9200') }}
    method: GET
    return_content: yes
  register: this
  until: "'You Know, for Search' in this.content"
  retries: 60
  delay: 10
