---
- name: Get consul leader
  uri:
    url: http://127.0.0.1:8500/v1/status/leader
    return_content: yes
  register: consulleader
  delegate_to: "{{ groups['consul'][0] }}"

- set_fact:
    consulleaderout: "{{ consulleader.json | string | regex_findall('\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b') }}"

- name: Get boostrap index
  shell: |
    /usr/local/bin/consul acl bootstrap 2>&1 | awk -F'index: ' '{print $2}' | sed 's/[^0-9]//g'
  register: boostrapidx
  delegate_to: "{{ consulleaderout[0] }}"

- name: Create
  copy:
    owner: consul
    dest: "{{ consul_data_dir }}/acl-bootstrap-reset"
    content: '{{ boostrapidx.stdout }}'
  delegate_to: "{{ consulleaderout[0] }}"

- name: Run boostrap event
  shell: |
    /usr/local/bin/consul acl bootstrap
  register: boostrapevent
  delegate_to: "{{ consulleaderout[0] }}"

- debug:
    msg: "{{ boostrapevent }}"
