---
- name: Get consul leader
  uri:
    url: http://127.0.0.1:8500/v1/status/leader
    return_content: yes
  register: this
  delegate_to: "{{ groups['consul'][0] }}"

- debug:
    msg: "{{ this.json | regex_findall('\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b') }}"
